# Generated by Django 3.1.7 on 2021-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20210601_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='selected_value',
            field=models.FloatField(default=0),
        ),
    ]
