# Generated by Django 3.1.7 on 2021-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_auto_20210601_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='selected_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='stock_close_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
